apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ai-sandbox
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: aisandbox-services
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - audit-service:8083
              - auth-service:8085
