package com.askapp.audit.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * A security-master reference-data record — the kind of slowly-changing, read-heavy data a
 * financial back office loads in bulk (batch) and everything else looks up. It carries the
 * standard cross-reference identifiers (ISIN/CUSIP/SEDOL) plus descriptive attributes; the data
 * is synthetic (generated by the ref-data ingestion), but shaped to read as genuine reference data.
 *
 * <p>Indexes back the query API in {@link com.askapp.audit.controller.RefDataController}:
 * {@code idx_secmaster_instrument} (the unique business key + point lookups),
 * {@code idx_secmaster_asset_class} and {@code idx_secmaster_currency} (the equality filters on the
 * listing). Hibernate runs {@code ddl-auto=none}, so the same indexes are created by the Liquibase
 * changeset {@code 003-create-security-master}.
 */
@Entity
@Table(name = "security_master", indexes = {
	@Index(name = "idx_secmaster_instrument", columnList = "instrument_id", unique = true),
	@Index(name = "idx_secmaster_asset_class", columnList = "asset_class"),
	@Index(name = "idx_secmaster_currency", columnList = "currency")
})
public class SecurityMaster extends AuditableEntity {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Schema(accessMode = Schema.AccessMode.READ_ONLY)
	private Long id;

	/** Stable business key (e.g. {@code SEC-000042}); unique across the master. */
	@Column(name = "instrument_id", nullable = false, unique = true)
	private String instrumentId;

	private String isin;

	private String cusip;

	private String sedol;

	private String name;

	/** EQUITY / BOND / ETF / FX — the coarse instrument classification the listing filters on. */
	@Column(name = "asset_class")
	private String assetClass;

	/** ISO 4217 currency code (USD, EUR, …). */
	private String currency;

	private BigDecimal price;

	/** Effective date this record's values are stated as of. */
	@Column(name = "as_of_date")
	private LocalDate asOfDate;

	protected SecurityMaster() {
	}

	public SecurityMaster(String instrumentId, String isin, String cusip, String sedol, String name,
			String assetClass, String currency, BigDecimal price, LocalDate asOfDate) {
		this.instrumentId = instrumentId;
		this.isin = isin;
		this.cusip = cusip;
		this.sedol = sedol;
		this.name = name;
		this.assetClass = assetClass;
		this.currency = currency;
		this.price = price;
		this.asOfDate = asOfDate;
	}

	public Long getId() {
		return id;
	}

	public String getInstrumentId() {
		return instrumentId;
	}

	public String getIsin() {
		return isin;
	}

	public String getCusip() {
		return cusip;
	}

	public String getSedol() {
		return sedol;
	}

	public String getName() {
		return name;
	}

	public String getAssetClass() {
		return assetClass;
	}

	public String getCurrency() {
		return currency;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public LocalDate getAsOfDate() {
		return asOfDate;
	}

}
